name: Auto tag

on:
  push:
    branches:
      - main

jobs:
  build_and_tag:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install venv
        run: poetry install
      - name: Set version
        run: |
          poetry self add poetry-git-version-plugin
          poetry set-git-version
      - name: Build
        run: poetry build
      - name: Test
        run: poetry run pytest
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: patch