name: Auto tag

on:
  push:
    branches:
      - main

jobs:
  build_and_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install Poetry
        run: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
      - name: Add Poetry to path
        run: echo "${HOME}/.poetry/bin" >> $GITHUB_PATH
      - name: Install venv
        run: poetry install
      - name: Test
        run: poetry run pytest
      # - name: Bump version and push tag
      #   id: tag_version
      #   uses: mathieudutour/github-tag-action@v5.6
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     default_bump: patch